import ReactDOM from 'react-dom'
import React, { useEffect, useContext } from 'react'
// import StepSequencer from '../components/StepSequencer/StepSequencer'
// import Distortion from '../components/Distortion/Distortion'
// import PingPong from '../components/PingPong/PingPong'
// import Reverb from '../components/Reverb/Reverb'
// import Mixer from '../components/Mixer/Mixer'
import styles from '../styles/Main.module.scss'
import Auth from '../components/Auth/Auth'
import { CTX } from '../context/Store'

function App() {
  const [, updateState] = useContext(CTX)

  useEffect(() => {
    window.addEventListener('mousedown', function () {
      updateState({ type: 'CHANGE_CLICK_ACTIVE', payload: true })
    })
    window.addEventListener('mouseup', function () {
      updateState({ type: 'CHANGE_CLICK_ACTIVE', payload: false })
    })
  }, [])

  // useEffect(() => {
  //   let subscribed = true
  //   if (subscribed) {
  //     const foundToken = localStorage.getItem('cleanbreak-token')
  //     if (!foundToken) {
  //       updateState({
  //         type: 'LOGOUT',
  //       })
  //     } else {
  //       const setAuthInfo = async () => {
  //         Axios.get('/auth/user', {
  //           headers: { 'x-auth-token': foundToken },
  //         })
  //           .then((result) => {
  //             if (result.data.err) {
  //               console.log('err: ', result.data.err)
  //             } else {
  //               updateState({
  //                 type: 'LOGIN',
  //                 payload: { user: result.data, token: foundToken },
  //               })
  //             }
  //           })
  //           .catch((err) => {
  //             updateState({
  //               type: 'LOGOUT',
  //             })
  //           })
  //       }
  //       setAuthInfo()
  //     }
  //   }
  //   return () => {
  //     subscribed = false
  //   }
  // }, [updateState])

  const closeAuth = () => {
    ReactDOM.render(<div />, document.getElementById('modal'))
  }

  const logout = () => {
    updateState({ type: 'LOGOUT' })
  }

  const login = (e) => {
    updateState(e)
  }

  const openAuth = () => {
    ReactDOM.render(
      <div className='modal'>
        <div className='modal-container'>
          <Auth CTX={CTX} closeAuth={closeAuth} login={login} />
        </div>
      </div>,
      document.getElementById('modal')
    )
  }

  return (
    <div className={styles.App}>
      {/* {!isLoggedIn && ( */}
      <button className='open-auth' onClick={openAuth}>
        login / register
      </button>
      {/* )} */}
      <div className={styles.background}></div>
      <div className={styles.componentsContainer}>
        <div className={styles.space}></div>
        <div className={styles.effectsContainer}>
          {/* <Mixer /> */}
          {/* <Distortion /> */}
          {/* <PingPong /> */}
          {/* <Reverb /> */}
        </div>
        <div className={styles.stepContainer}>
          {/* <StepSequencer openAuth={openAuth} /> */}
        </div>
      </div>
      <button className='logout-btn' onClick={logout}>
        logout
      </button>
      {/* {isLoggedIn && (
      )} */}
    </div>
  )
}

export default App

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Main.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
